// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhcKlTR03AHeNq4E4jRWQa42rh4xE85ww',
    appId: '1:1003406536692:web:82162697dc0852e93e13a1',
    messagingSenderId: '1003406536692',
    projectId: 'flashcards-17eef',
    authDomain: 'flashcards-17eef.firebaseapp.com',
    storageBucket: 'flashcards-17eef.appspot.com',
    measurementId: 'G-ZQCTEHYCPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUshfkaMz9qI0ZsoMc5hLM4lJNACzy8fk',
    appId: '1:1003406536692:android:adf5bf12f0d760e13e13a1',
    messagingSenderId: '1003406536692',
    projectId: 'flashcards-17eef',
    storageBucket: 'flashcards-17eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmWX1NEcZuDVH4qa7BKARzEyGJaF9G-i4',
    appId: '1:1003406536692:ios:3f9921a6691db6e43e13a1',
    messagingSenderId: '1003406536692',
    projectId: 'flashcards-17eef',
    storageBucket: 'flashcards-17eef.appspot.com',
    iosClientId: '1003406536692-bd6d0drk6j4q0afitbl6qr7i834no6p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmWX1NEcZuDVH4qa7BKARzEyGJaF9G-i4',
    appId: '1:1003406536692:ios:3f9921a6691db6e43e13a1',
    messagingSenderId: '1003406536692',
    projectId: 'flashcards-17eef',
    storageBucket: 'flashcards-17eef.appspot.com',
    iosClientId: '1003406536692-bd6d0drk6j4q0afitbl6qr7i834no6p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsApp',
  );
}
